// Code generated by github.com/ngicks/gommon/pkg/enum/cmd/generate_enum/generate_enum.go. DO NOT EDIT.
package example

import "os"

type EnumB struct {
	data any
}

func EnumBInt(val int) EnumB {
	return EnumB{
		data: val,
	}
}

func EnumBString(val string) EnumB {
	return EnumB{
		data: val,
	}
}

func EnumBOsFile(val *os.File) EnumB {
	return EnumB{
		data: val,
	}
}

type EnumBMatcher struct {
	Int     func(v int)
	String  func(v string)
	OsFile  func(v *os.File)
	Default func(v any)
}

func (e EnumB) Match(m EnumBMatcher) {
	switch x := e.data.(type) {
	case int:
		if m.Int != nil {
			m.Int(x)
			return
		}
	case string:
		if m.String != nil {
			m.String(x)
			return
		}
	case *os.File:
		if m.OsFile != nil {
			m.OsFile(x)
			return
		}
	}

	if m.Default != nil {
		m.Default(e.data)
		return
	}

	panic("non exhaustive match")
}
